### ISSUE TITLE
what's version for Microsoft Excel can run CPU.xlsx?

### ISSUE THREAD

**Issue by yeqizhang** [InkboxSoftware/excelCPU#13]
After compiled bouncingBall.s , I use WPS or office2016 Microsoft Excel open CPU.xlsx and change "read ROM" , and use F9 key,  but CPU.xlsx can not change Secreen area.   what's wrong?

**Comment by ea04lintong** [comment]
at least excel 2019,  which support switch function

**Comment by yeqizhang** [comment]
> at least excel 2019, which support switch function

it's useful, thank you very much! brother~
