### ISSUE TITLE
I NEED HELP WITH MY CODE IN PYTHON

### ISSUE THREAD

**Issue by PythonCoder09** [InkboxSoftware/excelCPU#8]
I can't find out what is wrong with this code. Can anyone help?
base_price = input("Enter cart total: ")

percent_discount = base_price - base_price * .15
fixed_discount = base_price - 12

final_price = min(fixed_discount, percent_discount)
print("Your best price is $" + final_price)

**Comment by br3nr** [comment]
ask chat gippety

**Comment by Ranjan8473** [comment]
# I amn't able to send file so, I am sending this comment. this is my first time to solve an issue on Github
base_price = float(input("Enter cart total: "))

percent_discount = base_price - base_price * 0.15
fixed_discount = base_price - 12.0

final_price = min(fixed_discount, percent_discount)
print("Your best price is $", final_price)

**Comment by aut-mn** [comment]
Here you go, happy Python learning (GitHub issues isn't the place to learn Python or get help with your code, btw)
```python
# Convert the input to an integer value (will fail if user inputs non-int value)
base_price = int(input("Enter cart total: "))

percent_discount = base_price - (base_price * .15)

# Don't give the customer a discount if their order is below $12
if base_price >= 13: fixed_discount = base_price - 12
else: fixed_discount = base_price

final_price = min(fixed_discount, percent_discount)
print(f"Your best price is ${final_price}") # Changed to string concatenation
```

**Comment by Ndjieudja** [comment]
what are you  want to do or what is your problem with this

**Comment by APrakashzb07** [comment]
base_price = float(input("Enter cart total: "))  # Here Converting the  input to float

percent_discount = base_price - base_price * 0.15
fixed_discount = base_price - 12

final_price = min(fixed_discount, percent_discount)
print("Your best price is $" + str(final_price))  # Here, Converting final_price to string for concatenation

#Here in this code,

#The input() function returns a string, so you need to convert base_price to a numeric type (e.g., float) to perform mathematical operations.
#When using the min() function, make sure that the values being compared are of the same type. In your case, fixed_discount and percent_discount are of different types, which can lead to unexpected results.
#Now, the base_price is converted to a float, and I've added a conversion of final_price to a string before printing it. This should resolve the issues in your code.

**Comment by himanshuCoder2** [comment]
# Convert input to float as it's received as a string
base_price = float(input("Enter cart total: "))

# Calculate discounts
percent_discount = base_price * 0.15
fixed_discount = 12

# Calculate final price
final_price = base_price - min(fixed_discount, percent_discount)

# Format and print the result
print("Your best price is $" + format(final_price, ".2f"))
Convert the base_price to float as the input is received as a string.
Changed the calculation of percent_discount to correctly calculate 15% of the base price.
fixed_discount is set to a fixed value of 12.
Calculated final_price by subtracting the minimum of fixed_discount and percent_discount from base_price.
Formatted the final price to two decimal places for a cleaner output.

**Comment by elsandosgrande** [comment]
What even…

**Comment by proce55or** [comment]
It's the Khan Academy [COURSE: INTRO TO COMPUTER SCIENCE - PYTHON](https://www.khanacademy.org/computing/intro-to-python-fundamentals)
 > 
[UNIT 1](https://www.khanacademy.org/computing/intro-to-python-fundamentals/x5279a44ae0ab15d6:computational-thinking-with-variables)
Lesson 4: Arithmetic expressions
